image: moritzheiber/docker-hugo

pages:
  before_script:
  - git submodule sync --recursive
  - git submodule update --init --recursive
  script:
  - hugo
  artifacts:
    paths:
    - public
  only:
  - master
