baseurl = "https://heiber.im"
languageCode = "en-us"
title = "musings about silly things"
MetaDataFormat = "toml"
canonifyurls = true
paginate = 10
editor = "vim"
theme = "hyde-x"
enableGitInfo = true

[author]
  name = "Moritz Heiber"
  email = "hello@heiber.im"
  github = "moritzheiber"

[params]
  truncate = true
  hideReadingTime = false
  home = "Home"

  tagline = "#ruby #rust #go #devops #diversity"
  github = "https://github.com/moritzheiber"
  mastodon = "https://mastodon.social/@moritzheiber"
  gravatarhash = "d490fa92eebb2f8a3dd7bb39cca4b632"
  highlight = "monokai-sublime"
  rss = true

[taxonomies]
  category = "categories"
