baseurl = "https://heiber.im"
languageCode = "en-us"
title = "Moritz Heiber"
metaDataFormat = "toml"
canonifyurls = true
paginate = 10
editor = "vim"
theme = "cactus"
enableGitInfo = true
copyright = "Licensed under CC-by-4.0"

[author]
name = "Moritz Heiber"

[markup]
noClasses = false
  [markup.highlight]
  style = "monokai"

[minify.tdewolff.html]
keepWhitespace = true

[params]
colorTheme = "dark"
css = ["css/custom.css"]
mainSections = "posts"
description = "Hi, I'm Moritz. My purpose in life seems to be trying to outsmart computers. I'm really bad at it most of the time. These are the artifacts I've collected along the way."
showAllPostsOnHomePage = false
postsOnHomePage = 5
tagsOverview = true
rss = true
gravatar = "hello@heiber.im"
show_updated = true
showProjectsList = true

[[params.social]]
  name = "mastodon"
  link = "https://mastodon.social/@moritzheiber"

[[params.social]]
  name = "github"
  link = "https://github.com/moritzheiber"

[[params.social]]
  name = "email"
  link = "hello+web@heiber.im"

[params.comments]
enabled = false

[[menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "about"
url = "/about"
weight = 2

[[menu.main]]
identifier = "media"
name = "media"
url = "/media"
weight = 3

[[menu.main]]
identifier = "blog"
name = "blog"
url = "/posts"
weight = 4

[[menu.footer]]
identifier = "imprint"
name = "imprint"
url = "/imprint"
weight = 5
top = false

[taxonomies]
category = "categories"
tags = "tags"
